# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74f901ef8cf118c31f3df1548e8f0ef925421111ba9e5311d1c048b015614c6d2d2630392af38610875889222d167143e12616524422f2ddf3589c7754104106

test:
  secret_key_base: 3a715a7afe2e9ff9d71863648612fdbb2d9995cd32d1c8a602b5011ee43bc8884968af6db8bf686fc554fef8f599c19c66cc71a2da173aee70dbbe91ad92ff61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
